language: node_js
node_js:
  - "stable"
notifications:
  webhooks:
    - http://savage.nonblocking.io/savage/travis
addons:
  sauce_connect: true
  hosts:
    - ads.localhost
    - iframe.localhost
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g gulp
after_failure: "cat /home/travis/sauce-connect.log"
script:
  - gulp presubmit
  - gulp lint
  - gulp build
  - gulp minify
  - gulp test --saucelabs
